# -*- coding: utf-8 -*-
"""Customer Segment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpjSi-yOtwOJydjlDbIICzFt_-J-434H
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

print("All libraries loaded successfully!")

from google.colab import files
import io

uploaded = files.upload()

uploaded_file_name = list(uploaded.keys())[0]
file_content = uploaded[uploaded_file_name]

df = pd.read_excel(io.BytesIO(file_content), engine='openpyxl')
print("Data loaded! Shape:", df.shape)

print("First 5 rows:")
print(df.head())

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("Total rows and columns:", df.shape)

print("\nMissing values per column:")
print(df.isnull().sum())

print("\nBasic statistics:")
print(df.describe())

print("Top 10 countries by transactions:")
print(df['Country'].value_counts().head(10))

print("\nTop 10 most purchased products:")
print(df['Description'].value_counts().head(10))

# Remove rows where CustomerID is missing
df = df.dropna(subset=['CustomerID'])

# Remove cancelled orders
# Cancelled orders have InvoiceNo starting with 'C'
df = df[~df['InvoiceNo'].astype(str).str.startswith('C')]

# Remove rows where Quantity or UnitPrice is zero or negative
df = df[df['Quantity'] > 0]
df = df[df['UnitPrice'] > 0]

# CustomerID to integer
df['CustomerID'] = df['CustomerID'].astype(int)

# InvoiceDate to datetime format
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

print("Data cleaned!")
print("Remaining rows:", df.shape[0])
print("Unique customers:", df['CustomerID'].nunique())

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

print("TotalPrice column created!")
print(df[['InvoiceNo', 'Quantity', 'UnitPrice', 'TotalPrice']].head())

df = df[df['Country'] == 'United Kingdom']

print("Filtered to UK customers only")
print("Remaining rows:", df.shape[0])
print("Unique customers:", df['CustomerID'].nunique())

df['Month'] = df['InvoiceDate'].dt.to_period('M')
monthly_sales = df.groupby('Month')['TotalPrice'].sum()

plt.figure(figsize=(13, 5))
monthly_sales.plot(kind='line', color='steelblue', linewidth=2, marker='o')
plt.title('Monthly Revenue Trend')
plt.xlabel('Month')
plt.ylabel('Total Revenue (£)')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

top_products = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(11, 5))
top_products.plot(kind='barh', color='coral', edgecolor='black')
plt.title('Top 10 Best Selling Products')
plt.xlabel('Total Quantity Sold')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

reference_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)

print("Reference date used:", reference_date)

rfm = df.groupby('CustomerID').agg(
    Recency   = ('InvoiceDate', lambda x: (reference_date - x.max()).days),
    Frequency = ('InvoiceNo',   'nunique'),
    Monetary  = ('TotalPrice',  'sum')
).reset_index()

rfm['Monetary'] = rfm['Monetary'].round(2)

print("\nRFM Table (first 5 rows):")
print(rfm.head())
print("\nRFM Table shape:", rfm.shape)

plt.figure(figsize=(14, 4))

plt.subplot(1, 3, 1)
plt.hist(rfm['Recency'], bins=30, color='steelblue', edgecolor='black')
plt.title('Recency Distribution')
plt.xlabel('Days Since Last Purchase')

plt.subplot(1, 3, 2)
plt.hist(rfm['Frequency'], bins=30, color='coral', edgecolor='black')
plt.title('Frequency Distribution')
plt.xlabel('Number of Orders')

plt.subplot(1, 3, 3)
plt.hist(rfm['Monetary'], bins=30, color='mediumseagreen', edgecolor='black')
plt.title('Monetary Distribution')
plt.xlabel('Total Spend (£)')

plt.tight_layout()
plt.show()

# Recency: fewer days = better = higher score
rfm['R_Score'] = pd.qcut(rfm['Recency'], q=4, labels=[4, 3, 2, 1])

# Frequency: more orders = better = higher score
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), q=4, labels=[1, 2, 3, 4])

# Monetary: more spend = better = higher score
rfm['M_Score'] = pd.qcut(rfm['Monetary'], q=4, labels=[1, 2, 3, 4])

# Convert to integers
rfm['R_Score'] = rfm['R_Score'].astype(int)
rfm['F_Score'] = rfm['F_Score'].astype(int)
rfm['M_Score'] = rfm['M_Score'].astype(int)


rfm['RFM_Score'] = rfm['R_Score'] + rfm['F_Score'] + rfm['M_Score']

print("RFM Scores assigned!")
print(rfm[['CustomerID', 'R_Score', 'F_Score', 'M_Score', 'RFM_Score']].head(10))

def rfm_label(score):
    if score >= 10:
        return 'Champions'
    elif score >= 8:
        return 'Loyal Customers'
    elif score >= 6:
        return 'At Risk'
    elif score >= 4:
        return 'Needs Attention'
    else:
        return 'Lost Customers'

rfm['RFM_Segment'] = rfm['RFM_Score'].apply(rfm_label)

print("RFM Segments:")
print(rfm['RFM_Segment'].value_counts())

plt.figure(figsize=(9, 5))
rfm_counts = rfm['RFM_Segment'].value_counts()

colors_rfm = ['#2ecc71', '#3498db', '#f39c12', '#e67e22', '#e74c3c']
rfm_counts.plot(kind='bar', color=colors_rfm, edgecolor='black')

plt.title('Number of Customers per RFM Segment')
plt.xlabel('RFM Segment')
plt.ylabel('Number of Customers')
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

from sklearn.preprocessing import StandardScaler

X = rfm[['Recency', 'Frequency', 'Monetary']]


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Data scaled and ready for clustering!")
print("Shape:", X_scaled.shape)

inertia = []

for k in range(1, 11):
    km = KMeans(n_clusters=k, random_state=42)
    km.fit(X_scaled)
    inertia.append(km.inertia_)

plt.figure(figsize=(9, 5))
plt.plot(range(1, 11), inertia, 'bo-', linewidth=2, markersize=8)
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method — Find Best K')
plt.grid(True, alpha=0.3)
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)
rfm['Cluster'] = kmeans.fit_predict(X_scaled)

print("Clustering done!")
print("\nCustomers per cluster:")
print(rfm['Cluster'].value_counts().sort_index())

colors = ['#e74c3c', '#3498db', '#2ecc71', '#f39c12']

plt.figure(figsize=(10, 6))

for i in range(4):
    cluster_data = rfm[rfm['Cluster'] == i]
    plt.scatter(
        cluster_data['Recency'],
        cluster_data['Monetary'],
        label=f'Cluster {i}',
        color=colors[i],
        s=60,
        alpha=0.7
    )

plt.xlabel('Recency (Days Since Last Purchase)')
plt.ylabel('Monetary (Total Spend £)')
plt.title('Customer Clusters — Recency vs Monetary')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

cluster_summary = rfm.groupby('Cluster').agg(
    Total_Customers = ('CustomerID',  'count'),
    Avg_Recency     = ('Recency',     'mean'),
    Avg_Frequency   = ('Frequency',   'mean'),
    Avg_Monetary    = ('Monetary',    'mean')
).round(1)

print("Cluster Summary:")
print(cluster_summary)

segment_names = {
    0: 'Lost Customers',
    1: 'High Value VIPs',
    2: 'At Risk Customers',
    3: 'Loyal Regulars'
}

rfm['Segment'] = rfm['Cluster'].map(segment_names)

print("Segments assigned!")
print(rfm['Segment'].value_counts())

plt.figure(figsize=(14, 4))

plt.subplot(1, 3, 1)
rfm.groupby('Segment')['Recency'].mean().sort_values().plot(
    kind='barh', color='steelblue', edgecolor='black')
plt.title('Avg Recency per Segment')
plt.xlabel('Days')

plt.subplot(1, 3, 2)
rfm.groupby('Segment')['Frequency'].mean().sort_values().plot(
    kind='barh', color='coral', edgecolor='black')
plt.title('Avg Frequency per Segment')
plt.xlabel('Number of Orders')

plt.subplot(1, 3, 3)
rfm.groupby('Segment')['Monetary'].mean().sort_values().plot(
    kind='barh', color='mediumseagreen', edgecolor='black')
plt.title('Avg Monetary per Segment')
plt.xlabel('Total Spend (£)')

plt.tight_layout()
plt.show()

df_merged = df.merge(rfm[['CustomerID', 'Segment']], on='CustomerID', how='left')

# Top 5 products for each segment
for segment in df_merged['Segment'].dropna().unique():
    print(f"\n{'='*50}")
    print(f"Top 5 Products — {segment}")
    print('='*50)
    top = (df_merged[df_merged['Segment'] == segment]
           .groupby('Description')['Quantity']
           .sum()
           .sort_values(ascending=False)
           .head(5))
    print(top.to_string())

df_merged['Month'] = df_merged['InvoiceDate'].dt.to_period('M').astype(str)

monthly_segment = df_merged.groupby(
    ['Month', 'Segment'])['TotalPrice'].sum().unstack().fillna(0)

plt.figure(figsize=(13, 6))
for col in monthly_segment.columns:
    plt.plot(monthly_segment.index, monthly_segment[col], marker='o', label=col, linewidth=2)

plt.title('Monthly Revenue by Customer Segment')
plt.xlabel('Month')
plt.ylabel('Total Revenue (£)')
plt.xticks(rotation=45)
plt.legend(title='Segment')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

strategies = {
    'High Value VIPs': {
        'Profile'  : 'Low recency, high frequency, high monetary',
        'Goal'     : 'Retain and reward — do not lose them',
        'Strategy' : 'VIP loyalty program, early access to new products, personal thank you',
        'Channel'  : 'Personalized email, dedicated support',
        'Priority' : '⭐⭐⭐⭐⭐ HIGHEST'
    },
    'Loyal Regulars': {
        'Profile'  : 'Medium recency, good frequency, decent spend',
        'Goal'     : 'Push them into VIP tier',
        'Strategy' : 'Bundle offers, referral bonuses, spending milestone rewards',
        'Channel'  : 'Email newsletters, SMS campaigns',
        'Priority' : '⭐⭐⭐⭐ HIGH'
    },
    'At Risk Customers': {
        'Profile'  : 'Have not purchased in a while, used to be active',
        'Goal'     : 'Win them back before they are fully lost',
        'Strategy' : 'Win-back email, strong discount offer, survey to understand why they left',
        'Channel'  : 'Email re-engagement, retargeting ads',
        'Priority' : '⭐⭐⭐ MEDIUM'
    },
    'Lost Customers': {
        'Profile'  : 'High recency, low frequency, low monetary',
        'Goal'     : 'Last attempt or deprioritize',
        'Strategy' : 'One final heavy discount campaign, then remove from active list',
        'Channel'  : 'Email only, low budget',
        'Priority' : '⭐⭐ LOW'
    }
}

for segment, info in strategies.items():
    print(f"\n{'='*55}")
    print(f"  SEGMENT : {segment}")
    print(f"{'='*55}")
    for key, value in info.items():
        print(f"  {key:10}: {value}")

priority_scores = {
    'High Value VIPs'   : 5,
    'Loyal Regulars'    : 4,
    'At Risk Customers' : 3,
    'Lost Customers'    : 2
}

plt.figure(figsize=(9, 5))
plt.barh(
    list(priority_scores.keys()),
    list(priority_scores.values()),
    color=['#2ecc71', '#3498db', '#f39c12', '#e74c3c'],
    edgecolor='black'
)
plt.xlabel('Business Priority Score (out of 5)')
plt.title('Which Segment Needs Most Attention?')
plt.xlim(0, 6)
plt.tight_layout()
plt.show()

print("="*55)
print("  CUSTOMER SEGMENTATION ")

print("="*55)

print(f"\n  Total Transactions Analysed : {len(df):,}")
print(f"  Unique Customers            : {rfm['CustomerID'].nunique():,}")
print(f"  Date Range                  : {df['InvoiceDate'].min().date()} to {df['InvoiceDate'].max().date()}")
print(f"  Total Revenue               : £{df['TotalPrice'].sum():,.2f}")
print(f"  K-Means Clusters Created    : 4")
print(f"  RFM Segments                : {rfm['RFM_Segment'].nunique()}")

print("\n  Cluster Breakdown:")

print(rfm['Segment'].value_counts().to_string())

print("\n  RFM Breakdown:")

print(rfm['RFM_Segment'].value_counts().to_string())